version: '3.8'
services:
  db:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=admin1234
      - MONGO_INITDB_DATABASE=my_db=fileupload
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    environment:
      - MONGO_URL=mongodb://mongoadmin:admin1234@db:27017/fileupload?authSource=admin
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  mongo-data:
